Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt -y upgrade
    sudo apt install -y python3-pip
    sudo apt install -y libpq-dev
    sudo pip3 install psycopg2
    sudo pip3 install Django
  SHELL

  config.vm.synced_folder ".", "/home/vagrant", type: "rsync",
    rsync__exclude: "Vagrantfile"

end
